manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson 
  projects:
    - remote: petejohanson
      name: zmk
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config
